# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66c0667cabdf21f87cdfabdf5eae1d82f438f026ad344f8b8d65f40c80a12dc1d66d0c63dcbe5289bed3d601aab9609eb85a775fb458b7c045dc2b27673ff53e

test:
  secret_key_base: 526423d6fbdff69a7945b9a511fbd989fe76c6cfa417adfe27178b033bfc0e5ff7816b7d4f375685ba0c89186919bb4628ee5d48f9039ff1be080a269337159e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
